FROM bitnami/spark:latest
# USER root
# RUN install_packages curl

# # Download necessary JARs
# RUN curl -o /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.901.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar && \
#     curl -o /opt/bitnami/spark/jars/hadoop-aws-3.3.1.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar && \
#     curl -o /opt/bitnami/spark/jars/hadoop-common-3.3.1.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.3.1/hadoop-common-3.3.1.jar && \
#     curl -o /opt/bitnami/spark/jars/postgresql-42.2.23.jar https://jdbc.postgresql.org/download/postgresql-42.2.23.jar

# USER 1001